name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: "Deploy to Digital Ocean"
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key
          chmod 600 ~/.ssh/deploy-key
          cat >>~/.ssh/config <<END
          Host my-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: Print project root directory
        run: ssh -i ~/.ssh/deploy-key $SSH_USER@$SSH_IP 'cd $PROJECT_ROOT && pwd'
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          PROJECT_ROOT: ${{ secrets.PROJECT_ROOT }}
          SSH_IP: ${{ secrets.SSH_IP }}
